HOST_AGENT:
  VISUAL_MODE: false
  REASONING_MODEL: true
  API_TYPE: "ollama"
  API_BASE: "http://localhost:11434"
  API_KEY: ""
  API_VERSION: ""
  API_MODEL: "minimax-m2:cloud"

APP_AGENT:
  VISUAL_MODE: true
  REASONING_MODEL: false
  API_TYPE: "ollama"
  API_BASE: "http://localhost:11434"
  API_KEY: ""
  API_VERSION: ""
  API_MODEL: "qwen3-vl:235b-cloud"

EVALUATION_AGENT:
  VISUAL_MODE: false
  REASONING_MODEL: true
  API_TYPE: "ollama"
  API_BASE: "http://localhost:11434"
  API_KEY: ""
  API_VERSION: ""
  API_MODEL: "deepseek-v3.1:671b-cloud"

BACKUP_AGENT:
  VISUAL_MODE: false
  API_TYPE: "ollama"
  API_BASE: "http://localhost:11434"
  API_KEY: ""
  API_VERSION: ""
  API_MODEL: "kimi-k2:1t-cloud"

OMNIPARSER:
  ENDPOINT: "http://xxx.xxx.xxx.xxx:xxxx"
  BOX_THRESHOLD: 0.05
  IOU_THRESHOLD: 0.1
  USE_PADDLEOCR: true
  IMGSZ: 640

MAX_TOKENS: 100000
MAX_RETRY: 3
TEMPERATURE: 0.6
TOP_P: 0.9
TIMEOUT: 60

RAG_OFFLINE_DOCS: true
RAG_OFFLINE_DOCS_RETRIEVED_TOPK: 3

BING_API_KEY: "YOUR_BING_SEARCH_API_KEY"
RAG_ONLINE_SEARCH: false
RAG_ONLINE_SEARCH_TOPK: 5
RAG_ONLINE_RETRIEVED_TOPK: 1

RAG_EXPERIENCE: true
RAG_EXPERIENCE_RETRIEVED_TOPK: 5

RAG_DEMONSTRATION: true
RAG_DEMONSTRATION_RETRIEVED_TOPK: 3
RAG_DEMONSTRATION_COMPLETION_N: 3
